# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-08 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201008_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
