# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-08 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
