# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=18),
        ),
    ]
