# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-02 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author2book',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='author2book',
            old_name='book',
            new_name='book_id',
        ),
        migrations.AlterUniqueTogether(
            name='author2book',
            unique_together=set([('author_id', 'book_id')]),
        ),
    ]
