# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-02 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_auto_20201102_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author2book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='author2book',
            old_name='book_id',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='author2book',
            unique_together=set([('author', 'book')]),
        ),
    ]
