# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-26 08:52
from __future__ import unicode_literals

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app01.models.MyCharField(max_length=12)),
                ('birthday', models.DateTimeField(verbose_name='生日')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3)),
            ],
        ),
    ]
