# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('pric', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fav_num', models.PositiveIntegerField()),
                ('sale_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=12)),
                ('addr', models.TextField()),
                ('birth_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Publisher'),
        ),
    ]
